CITIES = {
    "UZ": "🇺🇿",
    "RU": "🇷🇺",
    "US": "🇺🇸",
    "GB": "🇬🇧",
    "DE": "🇩🇪",
    "FR": "🇫🇷",
    "IT": "🇮🇹",
    "ES": "🇪🇸",
    "CN": "🇨🇳",
    "JP": "🇯🇵",
    "KR": "🇰🇷",
    "KZ": "🇰🇿",
    "KG": "🇰🇬",
    "TJ": "🇹🇯",
    "TM": "🇹🇲",
    "AE": "🇦🇪",
    "TR": "🇹🇷",
    "IN": "🇮🇳",
    "CA": "🇨🇦",
    "AU": "🇦🇺",
    "BR": "🇧🇷",
    "UA": "🇺🇦",
    "PL": "🇵🇱",
    "NL": "🇳🇱",
    "SE": "🇸🇪",
    "CH": "🇨🇭",
    "NO": "🇳🇴",
    "FI": "🇫🇮",
}

COUNTRIES = {
    "UZ":"O'zbekiston",
    "RU":"Rossiya",
    "US":"Amerika Qo'shma Shtatlari",
    "GB":"Angliya",
    "DE":"Germaniya",
    "FR":"Fransiya",
    "TR":"Turkiya",
    "KZ":"Qozog'iston",
    "KG":"Qirg'iziston",
    "TJ":"Tojikiston",
}